import type { SkillDefinition } from "../../core/skill-runtime.js";
import {
  MINECRAFT_COLLECT_BLOCK_CAPABILITY,
  MINECRAFT_CRAFT_CAPABILITY,
  MINECRAFT_EAT_CAPABILITY,
  MINECRAFT_HARVEST_BERRIES_CAPABILITY,
  MINECRAFT_PICKUP_ITEM_CAPABILITY,
  MINECRAFT_PLACE_TABLE_CAPABILITY,
  MINECRAFT_REST_CAPABILITY,
  MINECRAFT_MINE_BLOCK_CAPABILITY,
  MINECRAFT_PLACE_BLOCK_CAPABILITY,
  MINECRAFT_BUILD_SHELTER_CAPABILITY,
  MINECRAFT_ATTACK_HOSTILE_CAPABILITY,
  MINECRAFT_DROP_ITEM_CAPABILITY,
  MINECRAFT_EQUIP_CAPABILITY,
  MINECRAFT_INSPECT_BLOCK_CAPABILITY,
  MINECRAFT_LOOK_CAPABILITY,
  MINECRAFT_NAVIGATE_CAPABILITY,
  minecraftCollectBlockInputSchema,
  minecraftCraftItemInputSchema,
  minecraftEatFoodInputSchema,
  minecraftHarvestBerriesInputSchema,
  minecraftPickupItemInputSchema,
  minecraftPlaceTableInputSchema,
  minecraftRestInputSchema,
  minecraftMineBlockInputSchema,
  minecraftPlaceBlockInputSchema,
  minecraftBuildShelterInputSchema,
  minecraftAttackHostileInputSchema,
  minecraftDropItemInputSchema,
  minecraftEquipInputSchema,
  minecraftInspectBlockInputSchema,
  minecraftLookInputSchema,
  minecraftNavigateInputSchema,
} from "./capabilities.js";

export const minecraftSkills: readonly SkillDefinition[] = [
  {
    id: "minecraft.orient",
    description: "Safely orient the Minecraft player and confirm the local view state.",
    capability: MINECRAFT_LOOK_CAPABILITY,
    inputSchema: minecraftLookInputSchema,
  },
  {
    id: "minecraft.inspect-block",
    description: "Inspect a locally loaded block without modifying the world.",
    capability: MINECRAFT_INSPECT_BLOCK_CAPABILITY,
    inputSchema: minecraftInspectBlockInputSchema,
  },
  {
    id: "minecraft.navigate",
    description: "Reach a nearby coordinate with conservative pathfinding.",
    capability: MINECRAFT_NAVIGATE_CAPABILITY,
    inputSchema: minecraftNavigateInputSchema,
  },
  {
    id: "minecraft.collect-log",
    description: "Collect one observed log block and verify that its item entered inventory.",
    capability: MINECRAFT_COLLECT_BLOCK_CAPABILITY,
    inputSchema: minecraftCollectBlockInputSchema,
  },
  {
    id: "minecraft.equip-item",
    description: "Equip an inventory item into a selected equipment slot and verify it.",
    capability: MINECRAFT_EQUIP_CAPABILITY,
    inputSchema: minecraftEquipInputSchema,
  },
  {
    id: "minecraft.craft-item",
    description: "Craft only a supported plank, stick, crafting-table, or wooden tool item using verified inventory prerequisites.",
    capability: MINECRAFT_CRAFT_CAPABILITY,
    inputSchema: minecraftCraftItemInputSchema,
  },
  {
    id: "minecraft.eat-food",
    description: "Eat an allowlisted food when hunger is below the survival threshold and verify both hunger and inventory changes.",
    capability: MINECRAFT_EAT_CAPABILITY,
    inputSchema: minecraftEatFoodInputSchema,
  },
  {
    id: "minecraft.place-crafting-table",
    description: "Place a crafting table on a visible solid support block after local collision and danger checks.",
    capability: MINECRAFT_PLACE_TABLE_CAPABILITY,
    inputSchema: minecraftPlaceTableInputSchema,
  },
  {
    id: "minecraft.pickup-item",
    description: "Walk to an observed dropped food or log item and confirm that the item entered the inventory.",
    capability: MINECRAFT_PICKUP_ITEM_CAPABILITY,
    inputSchema: minecraftPickupItemInputSchema,
  },
  {
    id: "minecraft.harvest-berries",
    description: "Harvest one observed ripe sweet berry bush (age 2 or 3) and confirm that berries entered the inventory.",
    capability: MINECRAFT_HARVEST_BERRIES_CAPABILITY,
    inputSchema: minecraftHarvestBerriesInputSchema,
  },
  {
    id: "minecraft.rest",
    description: "Stand still for a bounded time while natural regeneration works; interrupted by threats or damage.",
    capability: MINECRAFT_REST_CAPABILITY,
    inputSchema: minecraftRestInputSchema,
  },
  {
    id: "minecraft.mine-block",
    description: "Mine one allowlisted stone-class or ore block with a tool check, and verify that its drop entered the inventory.",
    capability: MINECRAFT_MINE_BLOCK_CAPABILITY,
    inputSchema: minecraftMineBlockInputSchema,
  },
  {
    id: "minecraft.place-block",
    description: "Place one allowlisted block from inventory onto an observed support block and read it back.",
    capability: MINECRAFT_PLACE_BLOCK_CAPABILITY,
    inputSchema: minecraftPlaceBlockInputSchema,
  },
  {
    id: "minecraft.build-shelter",
    description: "Close the observed open sides around the player with blocks from inventory, one validated placement at a time.",
    capability: MINECRAFT_BUILD_SHELTER_CAPABILITY,
    inputSchema: minecraftBuildShelterInputSchema,
  },
  {
    id: "minecraft.attack-hostile",
    description: "Attack one identified hostile for a bounded number of swings, only when combat is enabled and the safety conditions hold.",
    capability: MINECRAFT_ATTACK_HOSTILE_CAPABILITY,
    inputSchema: minecraftAttackHostileInputSchema,
  },
  {
    id: "minecraft.drop-item",
    description: "Drop a small amount of allowlisted terrain from inventory to free slots; tools and food are refused.",
    capability: MINECRAFT_DROP_ITEM_CAPABILITY,
    inputSchema: minecraftDropItemInputSchema,
  },
];
