"""Unit tests for the launcher. They run offline: no Minecraft, no network beyond loopback sockets, and no real Node
process is started except where a test says so. WSL, Windows and missing-tool situations are produced by injecting the
environment, because none of them can be assumed to be present where the tests run."""

from __future__ import annotations

import io
import json
import os
import signal
import socket
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from launcher import checks, cli, process, wsl  # noqa: E402

WSL2_PROC = "Linux version 5.15.90.1-microsoft-standard-WSL2 (root@x) (gcc) #1 SMP"
WSL1_PROC = "Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0) #1"
NATIVE_PROC = "Linux version 6.1.0-18-amd64 (debian-kernel@lists.debian.org)"


class PlatformDetection(unittest.TestCase):
    def test_wsl2_is_recognised_from_the_kernel_string_and_from_wsl_variables(self) -> None:
        by_kernel = wsl.detect_platform("Linux", {}, WSL2_PROC)
        self.assertTrue(by_kernel.wsl)
        self.assertEqual(by_kernel.wsl_version, 2)
        by_env = wsl.detect_platform("Linux", {"WSL_DISTRO_NAME": "Ubuntu", "WSL_INTEROP": "/run/WSL/1_interop"}, NATIVE_PROC)
        self.assertTrue(by_env.wsl)
        self.assertEqual(by_env.distro, "Ubuntu")

    def test_wsl1_native_linux_windows_and_macos(self) -> None:
        self.assertEqual(wsl.detect_platform("Linux", {}, WSL1_PROC).wsl_version, 1)
        native = wsl.detect_platform("Linux", {}, NATIVE_PROC)
        self.assertFalse(native.wsl)
        self.assertIsNone(native.wsl_version)
        self.assertFalse(wsl.detect_platform("Windows", {"WSL_DISTRO_NAME": "x"}, WSL2_PROC).wsl, "inside Windows itself WSL markers mean nothing")
        self.assertEqual(wsl.detect_platform("Darwin", {}, None).system, "darwin")

    def test_unreadable_kernel_string_without_markers_is_not_wsl(self) -> None:
        self.assertFalse(wsl.detect_platform("Linux", {}, None).wsl)


class WindowsHostDiscovery(unittest.TestCase):
    def test_gateway_and_nameserver_are_parsed_and_deduplicated(self) -> None:
        route = "default via 172.28.0.1 dev eth0 proto kernel\n172.28.0.0/20 dev eth0 scope link"
        resolv = "# generated by WSL\nnameserver 127.0.0.53\nnameserver 172.28.0.1\nnameserver 8.8.8.8"
        self.assertEqual(wsl.parse_default_gateway(route), "172.28.0.1")
        self.assertEqual(wsl.parse_resolv_nameserver(resolv), "172.28.0.1", "loopback resolvers are skipped")
        self.assertEqual(wsl.windows_host_candidates(route, resolv), ["172.28.0.1"])
        self.assertEqual(wsl.windows_host_candidates("default via 10.0.0.1 dev eth0", "nameserver 10.0.0.2"), ["10.0.0.1", "10.0.0.2"])
        self.assertEqual(wsl.windows_host_candidates(None, None), [])

    def test_loopback_names(self) -> None:
        for name in ("localhost", "127.0.0.1", "127.9.9.9", "::1", "0.0.0.0"):
            self.assertTrue(wsl.is_loopback(name), name)
        for name in ("192.168.1.5", "mc.example.com", "172.28.0.1"):
            self.assertFalse(wsl.is_loopback(name), name)

    def test_probe_reports_open_and_refused_on_real_loopback_sockets(self) -> None:
        with socket.socket() as server:
            server.bind(("127.0.0.1", 0))
            server.listen(1)
            port = server.getsockname()[1]
            self.assertEqual(wsl.probe_tcp("127.0.0.1", port), "open")
        self.assertEqual(wsl.probe_tcp("127.0.0.1", port), "refused", "nothing listens once the socket is closed")


class HostChoice(unittest.TestCase):
    wsl2 = wsl.Platform("linux", True, 2, "Ubuntu")
    native = wsl.Platform("linux", False, None, None)

    @staticmethod
    def probe(open_hosts: set[str]):
        return lambda host, port: "open" if host in open_hosts else "refused"

    def test_an_explicit_or_environment_host_is_never_overridden(self) -> None:
        explicit = wsl.choose_host("10.1.1.1", None, 25565, self.wsl2, ["172.28.0.1"], self.probe({"172.28.0.1"}))
        self.assertEqual((explicit.host, explicit.changed), ("10.1.1.1", False))
        environment = wsl.choose_host(None, "mc.local", 25565, self.wsl2, ["172.28.0.1"], self.probe({"172.28.0.1"}))
        self.assertEqual((environment.host, environment.changed), ("mc.local", False))

    def test_under_wsl2_the_windows_host_is_used_only_when_loopback_is_silent_and_it_answers(self) -> None:
        decision = wsl.choose_host(None, None, 25565, self.wsl2, ["172.28.0.1"], self.probe({"172.28.0.1"}))
        self.assertEqual((decision.host, decision.changed), ("172.28.0.1", True))
        self.assertIn("using it", decision.notes[0])
        mirrored = wsl.choose_host(None, None, 25565, self.wsl2, ["172.28.0.1"], self.probe({"127.0.0.1", "172.28.0.1"}))
        self.assertEqual((mirrored.host, mirrored.changed), ("127.0.0.1", False), "mirrored networking keeps working unchanged")

    def test_when_nothing_answers_the_default_stays_and_the_note_explains_wsl(self) -> None:
        decision = wsl.choose_host(None, None, 25565, self.wsl2, ["172.28.0.1", "172.28.0.2"], self.probe(set()))
        self.assertEqual((decision.host, decision.changed), ("127.0.0.1", False))
        self.assertIn("172.28.0.1, 172.28.0.2", decision.notes[0])
        self.assertIn("--host", decision.notes[0])

    def test_outside_wsl2_nothing_is_probed_or_changed(self) -> None:
        def explode(host: str, port: int) -> str:
            raise AssertionError("must not probe")

        decision = wsl.choose_host(None, None, 25565, self.native, ["172.28.0.1"], explode)
        self.assertEqual((decision.host, decision.changed, decision.notes), ("127.0.0.1", False, ()))


class NodeAndDependencies(unittest.TestCase):
    def test_node_version_parsing_and_requirement(self) -> None:
        self.assertEqual(checks.parse_node_version("v22.22.3\n"), (22, 22, 3))
        self.assertIsNone(checks.parse_node_version("not a version"))
        self.assertEqual(checks.check_node("/usr/bin/node", (22, 0, 0)), [])
        too_old = checks.check_node("/usr/bin/node", (20, 11, 1))
        self.assertEqual(too_old[0].code, "NODE_TOO_OLD")
        self.assertIn("20.11.1", too_old[0].message)
        self.assertEqual(checks.check_node(None, None)[0].code, "NODE_MISSING")
        self.assertIn("https://nodejs.org", checks.check_node(None, None)[0].fix)
        self.assertEqual(checks.check_node("/x/node", None)[0].code, "NODE_VERSION_UNKNOWN")

    def test_executable_search_order_honours_an_explicit_node_and_windows_names(self) -> None:
        self.assertEqual(checks.node_candidates({"NODE": "/opt/node/bin/node"}, "linux"), ["/opt/node/bin/node", "node"])
        self.assertEqual(checks.node_candidates({}, "windows"), ["node.exe", "node"])
        found = checks.find_executable(["/definitely/not/here", "node"], which=lambda name: "/usr/bin/node" if name == "node" else None)
        self.assertEqual(found, "/usr/bin/node")
        self.assertIsNone(checks.find_executable(["node"], which=lambda name: None))
        with tempfile.NamedTemporaryFile() as handle:
            self.assertEqual(checks.find_executable([handle.name], which=lambda name: None), handle.name, "an absolute existing path is used directly")

    def make_project(self, root: Path, esbuild: list[str]) -> None:
        (root / "node_modules" / "tsx" / "dist").mkdir(parents=True)
        (root / "node_modules" / "tsx" / "dist" / "cli.mjs").write_text("")
        for name in esbuild:
            (root / "node_modules" / "@esbuild" / name).mkdir(parents=True)

    def test_dependencies_missing_wrong_platform_and_ok(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.assertEqual(checks.check_dependencies(root, "Linux", "x86_64")[0].code, "DEPENDENCIES_MISSING")
            self.make_project(root, ["win32-x64"])
            wrong = checks.check_dependencies(root, "Linux", "x86_64")
            self.assertEqual(wrong[0].code, "DEPENDENCIES_WRONG_PLATFORM")
            self.assertIn("another operating system", wrong[0].message)
            self.assertIn("npm ci", wrong[0].fix)
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.make_project(root, ["linux-x64"])
            self.assertEqual(checks.check_dependencies(root, "Linux", "x86_64"), [])
            self.assertEqual(checks.check_dependencies(root, "Linux", "aarch64")[0].code, "DEPENDENCIES_WRONG_PLATFORM")
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.make_project(root, [])
            self.assertEqual(checks.check_dependencies(root, "Linux", "x86_64"), [], "no platform packages to compare means nothing to complain about")

    def test_project_files_and_the_windows_mount_warning(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.assertEqual({problem.code for problem in checks.check_project(root)}, {"PROJECT_FILE_MISSING"})
            (root / "src").mkdir()
            (root / "package.json").write_text("{}")
            (root / "src" / "cli.ts").write_text("")
            self.assertEqual(checks.check_project(root), [])
        self.assertIn("Windows drive", checks.check_windows_mount(Path("/mnt/c/Users/me/GameMind"), True) or "")
        self.assertIsNone(checks.check_windows_mount(Path("/mnt/c/Users/me/GameMind"), False))
        self.assertIsNone(checks.check_windows_mount(Path("/home/me/GameMind"), True))


class PortsAndInstances(unittest.TestCase):
    def test_a_busy_default_port_moves_on_but_an_explicit_one_is_never_replaced(self) -> None:
        busy = {8787, 8788}
        is_free = lambda host, port: port not in busy  # noqa: E731
        self.assertEqual(checks.choose_control_port(8787, False, "127.0.0.1", is_free), (8789, None))
        port, problem = checks.choose_control_port(8787, True, "127.0.0.1", is_free)
        self.assertIsNone(port)
        self.assertEqual(problem.code if problem else None, "PORT_IN_USE")
        self.assertEqual(checks.choose_control_port(0, True, "127.0.0.1", is_free), (0, None))
        port, problem = checks.choose_control_port(8787, False, "127.0.0.1", lambda host, port: False, span=3)
        self.assertEqual((port, problem.code if problem else None), (None, "NO_FREE_PORT"))

    def test_real_port_probe(self) -> None:
        with socket.socket() as holder:
            holder.bind(("127.0.0.1", 0))
            holder.listen(1)
            self.assertFalse(checks.is_port_free("127.0.0.1", holder.getsockname()[1]))
        with socket.socket() as probe:
            probe.bind(("127.0.0.1", 0))
            free_port = probe.getsockname()[1]
        self.assertTrue(checks.is_port_free("127.0.0.1", free_port))

    def test_a_live_lock_means_already_running_and_a_dead_one_does_not(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            data = Path(raw)
            self.assertIsNone(checks.existing_instance(data))
            (data / "run").mkdir()
            (data / "run" / "gamemind.lock.json").write_text(json.dumps({"pid": 424242, "url": "http://127.0.0.1:8787/"}))
            self.assertEqual(checks.existing_instance(data, alive=lambda pid: True)["url"], "http://127.0.0.1:8787/")
            self.assertIsNone(checks.existing_instance(data, alive=lambda pid: False))
            (data / "run" / "gamemind.lock.json").write_text(json.dumps({"pid": os.getpid()}))
            self.assertIsNone(checks.existing_instance(data, alive=lambda pid: True), "our own pid is not another instance")
            (data / "run" / "gamemind.lock.json").write_text("{ torn")
            self.assertIsNone(checks.existing_instance(data, alive=lambda pid: True))


class FakeProcess:
    """A child that ignores the first N stop requests, to exercise the escalation ladder."""

    def __init__(self, survives: int = 0) -> None:
        self.pid = 4242
        self.survives = survives
        self.signals: list[str] = []
        self.returncode: int | None = None
        self.stdout = io.StringIO("")

    def poll(self) -> int | None:
        return self.returncode

    def terminate(self) -> None:
        self.signals.append("terminate")

    def kill(self) -> None:
        self.signals.append("kill")
        self.returncode = -9

    def send_signal(self, sig: int) -> None:
        self.signals.append(f"send:{sig}")
        self.survives -= 1
        if self.survives < 0:
            self.returncode = 0


@unittest.skipIf(os.name == "nt", "process-group signalling is POSIX-only; Windows uses taskkill")
class StoppingTheChild(unittest.TestCase):
    def test_a_child_that_exits_on_the_graceful_request_is_not_killed(self) -> None:
        child = FakeProcess(survives=0)
        sent: list[tuple[int, int]] = []
        with mock.patch("os.killpg", side_effect=lambda pid, sig: (sent.append((pid, sig)), setattr(child, "returncode", 0))):
            code = process.stop_process(child, grace=5, sleep=lambda s: None)  # type: ignore[arg-type]
        self.assertEqual(code, 0)
        self.assertEqual(sent, [(4242, signal.SIGINT)], "only the graceful signal was sent, to the whole process group")

    def test_a_child_that_ignores_the_request_is_escalated_to_term_and_then_kill(self) -> None:
        child = FakeProcess()
        sent: list[int] = []
        clock = {"t": 0.0}

        def fake_killpg(pid: int, sig: int) -> None:
            sent.append(sig)
            if sig == signal.SIGKILL:
                child.returncode = -9

        def fake_sleep(seconds: float) -> None:
            clock["t"] += 1.0

        with mock.patch("os.killpg", side_effect=fake_killpg):
            code = process.stop_process(child, grace=3, term_grace=2, sleep=fake_sleep, now=lambda: clock["t"])  # type: ignore[arg-type]
        self.assertEqual(sent, [signal.SIGINT, signal.SIGTERM, signal.SIGKILL])
        self.assertEqual(code, -9)

    def test_a_child_that_is_already_gone_is_left_alone(self) -> None:
        child = FakeProcess()
        child.returncode = 3
        with mock.patch("os.killpg", side_effect=AssertionError("no signal for a finished child")):
            self.assertEqual(process.stop_process(child, grace=1, sleep=lambda s: None), 3)  # type: ignore[arg-type]


class AgentArguments(unittest.TestCase):
    def parse(self, *argv: str):
        return cli.build_parser().parse_args(list(argv))

    def test_ready_line_parsing(self) -> None:
        line = 'GAMEMIND_READY {"url":"http://127.0.0.1:8787/","port":8787,"browser":{"requested":true,"opened":true}}'
        self.assertEqual(process.parse_ready_line(line)["port"], 8787)
        self.assertIsNone(process.parse_ready_line("GAMEMIND_READY not json"))
        self.assertIsNone(process.parse_ready_line("Control Center: http://127.0.0.1:8787/"))

    def test_command_uses_node_and_tsx_directly_with_no_shell(self) -> None:
        command = process.build_command("/usr/bin/node", Path("/proj"), ["--help"])
        self.assertEqual(command, ["/usr/bin/node", "/proj/node_modules/tsx/dist/cli.mjs", "/proj/src/cli.ts", "--help"])

    def test_default_is_a_persistent_live_session_that_opens_the_browser_once(self) -> None:
        args = self.parse()
        result = cli.agent_arguments(args, 8787, None)
        self.assertIn("--persistent", result)
        self.assertNotIn("--one-shot", result)
        self.assertIn("--open-browser", result)
        self.assertEqual(result[result.index("--control-port") + 1], "8787")
        self.assertEqual(result[result.index("--control-host") + 1], "127.0.0.1")
        self.assertNotIn("--sim", result)
        self.assertNotIn("--host", result, "an unset host is left to the agent (MINECRAFT_HOST or its default)")

    def test_options_map_onto_the_agent_flags(self) -> None:
        args = self.parse("--host", "mc.local", "--port", "25566", "--username", "Bot", "--version", "1.20.4", "--auth", "offline", "--task", "gather-logs", "--count", "3", "--resource", "oak_log", "--one-shot", "--no-autonomy", "--no-browser", "--", "--allow-combat")
        result = cli.agent_arguments(args, 9000, args.host)
        for pair in (["--host", "mc.local"], ["--port", "25566"], ["--username", "Bot"], ["--task", "gather-logs"], ["--count", "3"], ["--resource", "oak_log"]):
            index = result.index(pair[0])
            self.assertEqual(result[index : index + 2], pair)
        self.assertIn("--one-shot", result)
        self.assertIn("--no-autonomy", result)
        self.assertNotIn("--open-browser", result)
        self.assertEqual(result[-1], "--allow-combat")
        self.assertNotIn("--", result)

    def test_simulated_mode_uses_the_simulator_flag_and_no_server_flags(self) -> None:
        result = cli.agent_arguments(self.parse("--simulated", "food-remote-berries", "--host", "ignored"), 8787, "ignored")
        self.assertEqual(result[result.index("--sim") + 1], "food-remote-berries")
        self.assertNotIn("--host", result)
        self.assertEqual(cli.agent_arguments(self.parse("--simulated"), 8787, None)[1], "explore-remote-log")


def make_project(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "cli.ts").write_text("")
    (root / "package.json").write_text("{}")
    (root / "node_modules" / "tsx" / "dist").mkdir(parents=True)
    (root / "node_modules" / "tsx" / "dist" / "cli.mjs").write_text("")


class FakeChild:
    def __init__(self, lines: list[str], code: int = 0) -> None:
        self.stdout = io.StringIO("\n".join(lines) + "\n")
        self.pid = 999
        self._code = code

    def wait(self) -> int:
        return self._code

    def poll(self) -> int | None:
        return self._code


class MainFlow(unittest.TestCase):
    def run_main(self, argv: list[str], *, spawn_lines: list[str] | None = None, patch_node: str | None = "/usr/bin/node", env: dict | None = None):
        lines: list[str] = []
        spawned: list[list[str]] = []

        def fake_spawn(command, cwd, env=None):
            spawned.append(list(command))
            return FakeChild(spawn_lines or [])

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            make_project(root)
            patches = [
                mock.patch.object(checks, "find_executable", side_effect=lambda names, which=None: patch_node),
                mock.patch.object(checks, "node_version", return_value=(22, 22, 3)),
                mock.patch.object(checks, "is_port_free", return_value=True),
                mock.patch.object(checks, "check_dependencies", return_value=[]),
            ]
            for patch in patches:
                patch.start()
            try:
                code = cli.main(argv, root=root, env=env if env is not None else {}, out=lines.append, spawn_fn=fake_spawn)
            finally:
                mock.patch.stopall()
        return code, lines, spawned

    def test_check_mode_reports_the_environment_and_starts_nothing(self) -> None:
        code, lines, spawned = self.run_main(["--check"])
        self.assertEqual(code, 0)
        self.assertEqual(spawned, [])
        self.assertIn("Environment OK.", lines)
        self.assertTrue(any(line.startswith("Control port:") for line in lines))

    def test_missing_node_stops_before_anything_is_started_and_says_how_to_fix_it(self) -> None:
        code, lines, spawned = self.run_main([], patch_node=None)
        self.assertEqual(code, 2)
        self.assertEqual(spawned, [])
        text = "\n".join(lines)
        self.assertIn("Node.js was not found", text)
        self.assertIn("https://nodejs.org", text)

    def test_ready_line_becomes_a_friendly_banner_and_the_exit_code_is_the_childs(self) -> None:
        ready = 'GAMEMIND_READY ' + json.dumps({"url": "http://127.0.0.1:8787/", "port": 8787, "browser": {"requested": True, "opened": True, "method": "xdg-open", "reason": None}})
        code, lines, spawned = self.run_main(["--simulated", "--control-port", "8787"], spawn_lines=["starting", ready, "done"])
        self.assertEqual(code, 0)
        self.assertEqual(len(spawned), 1)
        self.assertIn("--open-browser", spawned[0])
        text = "\n".join(lines)
        self.assertIn("GameMind is running. Control Center: http://127.0.0.1:8787/", text)
        self.assertIn("Opened in your default browser (xdg-open)", text)
        self.assertNotIn("GAMEMIND_READY", text, "the machine-readable line is not echoed to the person")

    def test_a_browser_that_could_not_be_opened_is_reported_with_the_address(self) -> None:
        ready = 'GAMEMIND_READY ' + json.dumps({"url": "http://127.0.0.1:8787/", "browser": {"requested": True, "opened": False, "method": None, "reason": "No browser opener worked"}})
        _, lines, _ = self.run_main(["--simulated"], spawn_lines=[ready])
        text = "\n".join(lines)
        self.assertIn("could not be opened automatically (No browser opener worked)", text)
        self.assertIn("Open http://127.0.0.1:8787/ yourself.", text)

    def test_plain_start_opens_the_control_center_and_waits_for_the_page(self) -> None:
        code, _lines, spawned = self.run_main([])
        self.assertEqual(code, 0)
        self.assertIn("--no-connect", spawned[0], "no connection is made until the operator connects from the page")
        self.assertIn("--control-center", spawned[0])

    def test_an_explicit_host_or_task_or_simulator_still_connects_at_once(self) -> None:
        for argv in (["--host", "mc.local"], ["--port", "25566"], ["--task", "gather-logs"], ["--simulated"]):
            with self.subTest(argv=argv):
                _code, _lines, spawned = self.run_main(argv)
                self.assertNotIn("--no-connect", spawned[0])

    def test_a_connection_set_in_the_environment_counts_as_explicit(self) -> None:
        _code, _lines, spawned = self.run_main([], env={"MINECRAFT_HOST": "mc.local"})
        self.assertNotIn("--no-connect", spawned[0])

    def test_missing_dependencies_are_installed_without_asking_unless_no_install_is_given(self) -> None:
        calls: list[list[str]] = []
        with mock.patch.object(cli.subprocess, "run", side_effect=lambda cmd, **kw: calls.append(list(cmd)) or mock.Mock(returncode=0)), \
            mock.patch.object(checks, "check_dependencies", side_effect=[[checks.Problem("DEPENDENCIES_MISSING", "missing", "npm ci")], []]), \
            mock.patch.object(checks, "find_executable", return_value="/usr/bin/npm"), \
            mock.patch.object(checks, "node_version", return_value=(22, 22, 3)), \
            mock.patch.object(checks, "is_port_free", return_value=True), \
            mock.patch.object(cli, "ask", side_effect=lambda q, assume_yes, interactive: assume_yes), \
            mock.patch.object(checks, "check_node", return_value=[]):
            with tempfile.TemporaryDirectory() as raw:
                root = Path(raw)
                make_project(root)
                cli.main([ "--no-browser"], root=root, env={}, out=lambda _line: None, spawn_fn=lambda *a, **k: FakeChild([]))
        self.assertTrue(calls and calls[0][1] == "ci", "npm ci runs by default, without a prompt")

    def test_wsl2_with_only_the_windows_host_answering_uses_it_and_says_so(self) -> None:
        with mock.patch.object(wsl, "probe_tcp", side_effect=lambda host, port, timeout=1.5: "open" if host == "172.28.0.1" else "refused"), mock.patch.object(
            cli, "read_proc_version", return_value=WSL2_PROC
        ), mock.patch.object(cli, "discover_windows_host", return_value=["172.28.0.1"]), mock.patch("platform.system", return_value="Linux"):
            code, lines, spawned = self.run_main([])
        self.assertEqual(code, 0)
        self.assertEqual(spawned[0][spawned[0].index("--host") + 1], "172.28.0.1")
        self.assertIn("using it", "\n".join(lines))

    def test_an_explicit_host_is_passed_through_untouched_under_wsl2(self) -> None:
        with mock.patch.object(wsl, "probe_tcp", return_value="refused"), mock.patch.object(cli, "read_proc_version", return_value=WSL2_PROC), mock.patch.object(
            cli, "discover_windows_host", return_value=["172.28.0.1"]
        ), mock.patch("platform.system", return_value="Linux"):
            _, _, spawned = self.run_main(["--host", "192.168.1.50"])
        self.assertEqual(spawned[0][spawned[0].index("--host") + 1], "192.168.1.50")

    def test_a_running_instance_is_not_started_twice(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            make_project(root)
            (root / "data" / "run").mkdir(parents=True)
            (root / "data" / "run" / "gamemind.lock.json").write_text(json.dumps({"pid": 31337, "url": "http://127.0.0.1:8790/"}))
            lines: list[str] = []
            spawned: list = []
            with mock.patch.object(checks, "find_executable", return_value="/usr/bin/node"), mock.patch.object(checks, "node_version", return_value=(22, 1, 0)), mock.patch.object(
                checks, "check_dependencies", return_value=[]
            ), mock.patch.object(checks, "pid_alive", return_value=True):
                code = cli.main([], root=root, env={}, out=lines.append, spawn_fn=lambda *a, **k: spawned.append(a))
        self.assertEqual(code, 0)
        self.assertEqual(spawned, [])
        self.assertIn("already running", "\n".join(lines))
        self.assertIn("http://127.0.0.1:8790/", "\n".join(lines))

    def test_a_port_the_operator_asked_for_that_is_busy_is_an_error_not_a_silent_change(self) -> None:
        lines: list[str] = []
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            make_project(root)
            with mock.patch.object(checks, "find_executable", return_value="/usr/bin/node"), mock.patch.object(checks, "node_version", return_value=(22, 1, 0)), mock.patch.object(
                checks, "check_dependencies", return_value=[]
            ), mock.patch.object(checks, "is_port_free", return_value=False):
                code = cli.main(["--control-port", "8787"], root=root, env={}, out=lines.append, spawn_fn=lambda *a, **k: None)
        self.assertEqual(code, 2)
        self.assertIn("Control Center port 8787 is already in use", "\n".join(lines))


class OptionalToolsTest(unittest.TestCase):
    def _run(self, outputs):
        def fake_run(argv, **kwargs):
            key = argv[0].rsplit("/", 1)[-1]
            text = outputs.get(key)
            if text is None:
                raise OSError("missing")
            return mock.Mock(returncode=text[0], stdout=text[1], stderr=text[2])
        return fake_run

    def test_missing_tools_are_reported_but_never_block(self):
        tools = checks.check_optional_tools("Linux", which=lambda name: None, run=self._run({}))
        self.assertEqual([t.name for t in tools], ["Java", "Docker"])
        self.assertTrue(all(not t.found for t in tools))
        self.assertIn("not found", tools[1].render())

    def test_java_version_is_read_from_stderr(self):
        which = {"java": "/usr/bin/java", "docker": None}
        tools = checks.check_optional_tools(
            "Linux",
            which=lambda name: which.get(name),
            run=self._run({"java": (0, "", 'openjdk version "21.0.2" 2024-01-16\n')}),
        )
        self.assertTrue(tools[0].found)
        self.assertIn("21.0.2", tools[0].version)

    def test_docker_installed_but_engine_down_says_so(self):
        which = {"docker": "/usr/bin/docker"}
        tools = checks.check_optional_tools(
            "Linux",
            which=lambda name: which.get(name),
            run=self._run({"docker": (1, "", "Cannot connect to the Docker daemon")}),
        )
        docker = tools[1]
        self.assertFalse(docker.found)
        self.assertIn("engine does not answer", docker.hint)

    def test_docker_with_running_engine_is_found(self):
        which = {"docker": "/usr/bin/docker"}
        tools = checks.check_optional_tools(
            "Linux",
            which=lambda name: which.get(name),
            run=self._run({"docker": (0, "27.3.1\n", "")}),
        )
        self.assertTrue(tools[1].found)
        self.assertIn("27.3.1", tools[1].version)


if __name__ == "__main__":
    unittest.main()
